#!/usr/bin/env python3
"""Generate deps/python-wheels.lock: pure-python wheels (py3-none-any) for the Python
site-packages that Blender 5.2.2's deps builder installs, at exactly the versions pinned
in build_files/build_environment/cmake/versions.cmake, with PyPI's sha256.

Usage: gen_wheel_lock.py <path/to/versions.cmake> > deps/python-wheels.lock
"""
import json, re, sys, urllib.request

PKGS = {  # pip name -> versions.cmake variable
    "setuptools": "SETUPTOOLS_VERSION", "meson-python": "MESON_PYTHON_VERSION",
    "packaging": "PACKAGING_VERSION", "pyproject-metadata": "PYPROJECT_METADATA_VERSION",
    "idna": "IDNA_VERSION", "charset-normalizer": "CHARSET_NORMALIZER_VERSION",
    "urllib3": "URLLIB3_VERSION", "certifi": "CERTIFI_VERSION", "requests": "REQUESTS_VERSION",
    "autopep8": "AUTOPEP8_VERSION", "pycodestyle": "PYCODESTYLE_VERSION",
    "docutils": "DOCUTILS_VERSION", "meson": "MESON_VERSION", "attrs": "ATTRS_VERSION",
    "cattrs": "CATTRS_VERSION", "fastjsonschema": "FASTJSONSCHEMA_VERSION",
    "typing-extensions": "TYPING_EXTENSIONS_VERSION", "tomli-w": "TOMLI_W_VERSION",
    "setuptools-scm": "SETUPTOOLS_SCM_VERSION",
}
text = open(sys.argv[1]).read()
def ver(var):
    return re.search(r"set\(%s ([^)\s]+)" % var, text).group(1)

print("# name url sha256  -- generated by scripts/tools/gen_wheel_lock.py from Blender 5.2.2 versions.cmake")
for name, var in PKGS.items():
    v = ver(var)
    for cand in (v, v + ".0"):
        try:
            d = json.load(urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{cand}/json"))
            break
        except Exception:
            d = None
    if d is None:
        sys.exit(f"not found: {name} {v}")
    wheels = [u for u in d["urls"] if u["packagetype"] == "bdist_wheel" and u["filename"].endswith("-none-any.whl")]
    if not wheels:
        sys.exit(f"no pure wheel: {name} {v}")
    w = wheels[0]
    print(f"{name}=={d['info']['version']} {w['url']} {w['digests']['sha256']}")
