#!/usr/bin/env python3
"""Generate DEPENDENCIES.md: every third-party source used by the build, with version,
URL, the hash Blender pins (MD5/SHA1/SHA256 as in versions.cmake), the sha256 of the file
actually downloaded and verified, and the license.

Usage: gen_manifest.py <blender-src> <packages-dir> <wheel-lock> > DEPENDENCIES.md
"""
import hashlib, os, re, sys

src, pkgdir, wheel_lock = sys.argv[1:4]
text = open(os.path.join(src, "build_files/build_environment/cmake/versions.cmake")).read()
text = re.sub(r"\[=\[.*?\]=\]", '""', text, flags=re.S)   # multi-line copyright blocks
vars_ = {}
for m in re.finditer(r"^\s*set\((\w+)\s+(.*?)\)\s*(#.*)?$", text, flags=re.M):
    k, v = m.group(1), m.group(2).strip()
    if v.startswith('"') and v.endswith('"'):
        v = v[1:-1]
    vars_[k] = v
def expand(v, depth=0):
    if depth > 10:
        return v
    return re.sub(r"\$\{(\w+)\}", lambda m: expand(vars_.get(m.group(1), m.group(0)), depth + 1), v)
def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()

deps = sorted(k[:-5] for k in vars_ if k.endswith("_FILE") and k[:-5] + "_URI" in vars_)
print("# Third-party dependency manifest\n")
print("Generated by `scripts/tools/gen_manifest.py` from Blender 5.2.2 "
      "`build_files/build_environment/cmake/versions.cmake` (with this fork's patches applied) "
      "and the files actually downloaded by the deps builder. The *pinned hash* is what Blender "
      "pins and the builder verifies (`FORCE_CHECK_HASH=ON` at configure and `URL_HASH` at extract); "
      "*sha256* is of the verified file. A `-` sha256 means the package was not downloaded (not used "
      "on this platform).\n")
print("| Name | Version | URL | Pinned hash | sha256 (downloaded) | License |")
print("|---|---|---|---|---|---|")
for d in deps:
    f = expand(vars_[d + "_FILE"]); url = expand(vars_[d + "_URI"])
    ver = expand(vars_.get(d + "_VERSION", ""))
    ht = vars_.get(d + "_HASH_TYPE", "?"); hv = expand(vars_.get(d + "_HASH", "?"))
    lic = expand(vars_.get(d + "_LICENSE", "")).replace("SPDX:", "")
    if not lic and d.startswith("ISPC"):
        lic = "BSD-3-Clause"   # not recorded in versions.cmake
    if not ver and d == "ISPC_PREBUILT":
        ver = expand(vars_["ISPC_VERSION"]) + " (aarch64 release binary)"
    p = os.path.join(pkgdir, f)
    s = sha256(p) if os.path.exists(p) else "-"
    print(f"| {d} | {ver} | {url} | {ht}:`{hv}` | `{s}` | {lic} |")

print("\n## Other pinned inputs\n")
print("| Name | Pin | Source | License |")
print("|---|---|---|---|")
print("| Blender | v5.2.2, git commit `d13f752e3b9c4f8c261cda552b1021f8bcc0382c` | https://projects.blender.org/blender/blender.git | GPL-2.0-or-later |")
print("| OptiX headers | v9.0.0, git commit `fff65c2a7c592f1ea5f1661ad7d2381cf965f9bd` | https://github.com/NVIDIA/optix-dev | NVIDIA SDK license (headers only, not redistributed in the build output) |")
print("| Build image | `nvcr.io/nvidia/cuda:13.0.3-devel-ubuntu24.04@sha256:2396393dc8a031a6faf810894ec8e40c8d80e2a1177cfda0c2bf81acac9aa240` (arm64) | NVIDIA NGC | NVIDIA Deep Learning Container License + Ubuntu |")
print("\n## Python wheels (bundled site-packages, `deps/python-wheels.lock`)\n")
print("| Package | URL | sha256 |")
print("|---|---|---|")
for line in open(wheel_lock):
    if line.startswith("#") or not line.strip():
        continue
    n, u, h = line.split()
    print(f"| {n} | {u} | `{h}` |")
